version: '2'
services:
    stratangbackendgateway-app:
        image: stratangbackendgateway
        environment:
            # - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://stratangbackendgateway-postgresql:5432/stratangbackendgateway
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8085:8085
    stratangbackendgateway-postgresql:
        extends:
            file: postgresql.yml
            service: stratangbackendgateway-postgresql
